### ISSUE TITLE
Textures for higher levels of towers

### ISSUE THREAD

**Issue by andrewkatson** [andrewkatson/TheBTeam#20]
the textures for lvl 2 and lvl 3 of all towers if possible

**Comment by jeremyelkayam** [comment]
Textures made for SkinnyKidUnit, Pepperoni, MeatLovers, DeepDish. Others coming soon

**Comment by jeremyelkayam** [comment]
FatKid, Gravy, EnergyDrink, SpicyFry

**Comment by jeremyelkayam** [comment]
I did the rest: Slushie, WaffleFry, CrinkleFry, NormalM&M, PeanutM&M, PeanutButterM&M. All textures are done
