### ISSUE TITLE
Sound Manager

### ISSUE THREAD

**Issue by andrewkatson** [andrewkatson/TheBTeam#21]
Implement the sound manager so that it loads in all sounds (paths defined in xml file). have sound play events made that will be made for units attacking, units dying, game startup, game end, and game playing

**Comment by andrewkatson** [comment]
reassigned to jeremy

**Comment by jeremyelkayam** [comment]
added lots of sound effects

**Comment by jeremyelkayam** [comment]
Added music. Sound Manager is done and easily extensible by adding more sounds to the xml and either raising PlaySoundEvents or creating delegates for other events inside of SoundManager.
